[package]
name = "media-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ffmpeg-next = { version = "7.0.4", features = ["default", "build"] }
stabby = { version = "36.1.1", features = ["default", "libloading"] }
media-types = { path = "../media-types" }
image = { version = "0.25.2", features = ["png"] }
mozjpeg = "0.10.10"
